# -*- coding: utf-8 -*-
"""CS Map Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19cSpyrvp2l5aGvS3RZ_OhOKLo-RG-mtL
"""

from collections import deque

import streamlit as st

class Node:

    def __init__(self, name):

        self.name = name

        self.neighbors = []



    def search(self, neighbor):

      for i in range(len(self.neighbors)):

        if neighbor == self.neighbors[i]:

          return True



      return False





    def findpath(self, Final):

      initial = self

      queue = [(initial, [initial.name])]

      checked = {initial}



      while queue:

        current, path = queue.pop(0)

        for element in current.neighbors:

          if element not in checked:

            npath = path + [element.name]



            if element == Final:

              return npath



            checked.add(element)

            queue.append((element, npath))



      return ["n/a"]
TURN_RULES = {
    # Leaving Officehall through Commons
    ("Music Hallway", "Math Hallway"): "turn left at the intersection",
    ("Math Hallway", "Music Hallway"): "turn right at the intersection",
    ("Math Hallway", "Science Hallway"): "turn right at the intersection",
    ("Science Hallway", "Math Hallway"): "turn left at the intersection",
    ("Math Hallway", "Commons Hallway"): "go straight through the intersection",
    ("Commons Hallway", "Math Hallway"): "go straight through the intersection",
    ("Math Hallway", "Language Hallway"): "turn left at the intersection",
    ("Language Hallway", "Math Hallway"): "turn right at the intersection",
    ("Commons Hallway", "General Hallway"): "turn right at the intersection",
    ("General Hallway", "Commons Hallway"): "turn left at the intersection",
    ("Commons Hallway", "Office Hallway"): "turn left at the intersection",
    ("Commons Hallway", "Language Hallway"): "turn right at the intersection",
    ("Language Hallway", "Commons Hallway"): "turn left at the intersection",
    ("Language Hallway", "Science Hallway"): "go straight through the intersection",
    ("Commons Hallway", "Science Hallway"): "turn left at the intersection",
    ("Science Hallway", "Language Hallway"): "go straight through the intersection",
    ("Science Hallway", "Commons Hallway"): "turn right at the intersection",
    ("General Hallway", "Office Hallway"): "go straight through the intersection",
    ("Office Hallway", "General Hallway"): "go straight through the intersection",
    ("General Hallway", "Library Hallway"): "turn right at the intersection",
    ("Library Hallway", "General Hallway"): "turn left at the intersection",
    ("Science Hallway", "Library Hallway"): "turn left at the intersection",
    ("Library Hallway", "Science Hallway"): "turn right at the intersection",
    ("Office Hallway", "Cafeteria"): "Go through the Cafeteria",
    ("Cafeteria", "Office Hallway"): "Go through the Cafeteria",
    ("", ""): "",
    ("", ""): "",

}

#Functions were created by Vishal



Math = Node("Math Hallway")

Science = Node("Science hallway")

Music = Node("Music Hallway")

Language = Node("Language Hallway")

Commons = Node("Commons Hallway")

Officehall = Node("Office Hallway")

General = Node("General Hallway")

Libraryhall = Node("Library Hallway")

Rm1 = Node("Room 1")

Rm2 = Node("Room 2")

Rm3 = Node("Room 3")

Rm4 = Node("Room 4")

Rm5 = Node("Room 5")

Rm6 = Node("Room 6")

Rm7 = Node("Room 7")

Rm8 = Node("Room 8")

Rm9 = Node("Room 9")

Rm10 = Node("Room 10")

Rm11 = Node("Room 11")

Rm12 = Node("Room 12")

Rm14 = Node("Room 14")

Rm16 = Node("Room 16")

Rm23 = Node("Room 23")

Rm24 = Node("Room 24")

Rm26 = Node("Room 26")

Rm27 = Node("Room 27")

Rm28 = Node("Room 28")

Rm29 = Node("Room 29")

Rm30 = Node("Room 30")

Rm31 = Node("Room 31")

Rm32 = Node("Room 32")

Rm33 = Node("Room 33")

Rm34 = Node("Room 34")

Rm35 = Node("Room 35")

Rm36 = Node("Room 36")

Rm37 = Node("Room 37")

Rm38 = Node("Room 38")

Gym = Node("Gym")

Cafeteria = Node("Cafeteria")

Stage = Node("Stage")

Library = Node("Library")

Counsellors = Node("Counsellors")

Office = Node("Office")





Math.neighbors = [Music, Science, Language, Commons]

Science.neighbors = [Libraryhall, Math, Commons, Language]

Music.neighbors = [Math]

Language.neighbors = [Math, Commons, Science]

Commons.neighbors = [Math, Science, General, Officehall, Language]

Officehall.neighbors = [Commons, General]

General.neighbors = [Officehall, Commons, Libraryhall]

Libraryhall.neighbors = [Science, General]










Math.neighbors.append(Rm36)

Math.neighbors.append(Rm33)



Science.neighbors.append(Rm31)

Science.neighbors.append(Rm30)

Science.neighbors.append(Rm33)

Science.neighbors.append(Rm32)

Science.neighbors.append(Rm24)

Science.neighbors.append(Rm27)

Science.neighbors.append(Rm26)

Science.neighbors.append(Rm28)

Science.neighbors.append(Rm29)





Music.neighbors.append(Rm37)

Music.neighbors.append(Rm38)



Libraryhall.neighbors.append(Library)

Libraryhall.neighbors.append(Rm16)



Language.neighbors.append(Rm34)

Language.neighbors.append(Rm35)



Commons.neighbors.append(Rm2)

Commons.neighbors.append(Gym)



General.neighbors.append(Rm3)

General.neighbors.append(Rm4)

General.neighbors.append(Rm5)

General.neighbors.append(Rm6)

General.neighbors.append(Rm7)

General.neighbors.append(Rm8)

General.neighbors.append(Rm9)

General.neighbors.append(Rm10)

General.neighbors.append(Rm11)

General.neighbors.append(Rm12)



Officehall.neighbors.append(Rm1)

Officehall.neighbors.append(Counsellors)

Officehall.neighbors.append(Office)

Officehall.neighbors.append(Cafeteria)

Officehall.neighbors.append(Stage)



allhallways =[Math, Science, Music, Language, Commons, Officehall, General, Libraryhall]



for hall in allhallways:

  for room in hall.neighbors:

    if hall not in room.neighbors:

      room.neighbors.append(hall)







Current = st.selectbox(

    "Where are you starting?",

    (

        "Rm1", "Rm2", "Rm3", "Rm4", "Rm5", "Rm6", "Rm7", "Rm8", "Rm9", "Rm10",

        "Rm11", "Rm12", "Rm14", "Rm16", "Rm23", "Rm24", "Rm26", "Rm27", "Rm28",

        "Rm29", "Rm30", "Rm31", "Rm32", "Rm33", "Rm34", "Rm35", "Rm36", "Rm37", "Rm38",

        "Gym", "Cafeteria", "Stage", "Library", "Counsellors", "Office"

    )

)

Next = st.selectbox(

    "Where are you Going?",

    (

        "Rm1", "Rm2", "Rm3", "Rm4", "Rm5", "Rm6", "Rm7", "Rm8", "Rm9", "Rm10",

        "Rm11", "Rm12", "Rm14", "Rm16", "Rm23", "Rm24", "Rm26", "Rm27", "Rm28",

        "Rm29", "Rm30", "Rm31", "Rm32", "Rm33", "Rm34", "Rm35", "Rm36", "Rm37", "Rm38",

        "Gym", "Cafeteria", "Stage", "Library", "Counsellors", "Office"

    )

)


Start = globals()[Current]

Destination = globals()[Next]

Path = Start.findpath(Destination)
for i in range(1, len(Path) - 1):
    curr_node = Path[i]
    next_node = Path[i + 1]

    action = TURN_RULES.get(
        (curr_node, next_node),
         "Continue through",  # Default fallback if rule isn't mapped
        )

    st.write("At", curr_node, action, "towards", next_node)
if len(Path) > 1:
    st.write("Arrive at ", Path[-1])